FROM oven/bun:1

WORKDIR /app

COPY ./packages  ./packages
COPY ./package.json  ./package.json
COPY ./bun.lock   ./bun.lock
COPY ./turbo.json   ./turbo.json
COPY ./apps/backend/package.json ./apps/backend/package.json 

RUN npm install

COPY ./apps/backend ./apps/backend

 RUN bun install 

 RUN bun run db:migrate

 RUN bun run build

 EXPOSE 8000

 CMD [ "bun", "run", "start:backend" ]


